### ISSUE TITLE
Use multiples of 4

### ISSUE THREAD

**Issue by zAlweNy26** [FedeDC512/asp-bookstore#2]
It's a good practice to use multiples of 4 in CSS. You noob

https://github.com/FedeDC512/asp-bookstore/blob/d0784cd8b825195bd14e6bd603c3c87a6ff28974/styles.css#L147
https://github.com/FedeDC512/asp-bookstore/blob/d0784cd8b825195bd14e6bd603c3c87a6ff28974/styles.css#L243

**Comment by FedeDC512** [comment]
In Japan 4 means Death and I do not want to offend anyone

**Comment by zAlweNy26** [comment]
So use the `rem` unit instead. CHECK MATE
